# Generated by Django 5.2.4 on 2025-08-13 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_completed',
        ),
    ]
