# Generated by Django 5.2.4 on 2025-08-07 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='assigned_to',
            field=models.ManyToManyField(to='tasks.participant'),
        ),
    ]
