# Generated by Django 5.2.4 on 2025-08-13 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_event_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='assigned_to',
        ),
    ]
