# Generated by Django 5.2.4 on 2025-08-11 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_event_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetail',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='details', to='tasks.event'),
        ),
    ]
