# Generated by Django 5.2.4 on 2025-08-13 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_event_assigned_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
